### ISSUE TITLE
Add Tier-list generator

### ISSUE THREAD

**Issue by Yamnasm** [Yamnasm/moviesmash#4]
Parse the history.json and add thresholds to sort each movie into a tierlist.

Tier list threshold will follow a strict bell-curve (ie, few S-tier, few E-tier movies and lots of C-tiers).

Generate the classic tier list using PIL.

**Comment by a11yk4t** [comment]
no

**Comment by a11yk4t** [comment]
the tier list generator has been made but it doesn't check by weight and instead receives an already sorted tiered list of movies
